### ISSUE TITLE
Update Readme.md : Add some screenshot of website

### ISSUE THREAD

**Issue by kavania2002** [kavania2002/MobiMart#1]
You can add some screenshots of the website for better reach and understanding.

1. Main page Page
2. Shopping cart Page
3. Address Form Page

**Comment by vishwast03** [comment]
Hey @kavania2002
I am Vishwas Tyagi. I would like to work on this.

**Comment by kavania2002** [comment]
The contest hasn't started yet, so I need to confirm from the team, whether to accept or not.

**Comment by kavania2002** [comment]
I will surely assign it to you don't worry.

**Comment by kavania2002** [comment]
Hey, I asked the team, they said not to accept any issues or pr's, you have to work upon this after 13th only, Then only your points will be counted. If you just want to learn and not behind any points then you can surely work. Just confirm here if you are working or not.

**Comment by vishwast03** [comment]
Thanks @kavania2002 for your reply.
I will work on this project after 13th. Please make sure to assign it to me.

**Comment by kavania2002** [comment]
Hey @vishwast03 you can start working now. Please finish within 3 days.

**Comment by vishwast03** [comment]
@kavania2002 Thanks for assigning this project to me.
I will try to complete it as soon as possible.

**Comment by kavania2002** [comment]
Good and enjoy coding.
