### ISSUE TITLE
Add CONTRIBUTING.md file

### ISSUE THREAD

**Issue by muthuannamalai12** [kavania2002/MobiMart#12]
I would like to add a CONTRIBUTING.mdfile which will contain all contributing guidelines and all git workflow so that all newbies or beginners and even experts can look into it and also the contributors will understand the workflow

**Comment by muthuannamalai12** [comment]
I would love to work on it as a part of Cross Woc. Kindly assign it to me.

**Comment by kavania2002** [comment]
Sorry to say, but it's already there in .github 
But I think you can updated things if you want. Look into it and give me suggestions, what you want update, on that basis I will decide whether to assign it or not.

**Comment by muthuannamalai12** [comment]
1.We can add Github documentation links for 
i). Getting started with Git and GitHub
ii). Forking a Repo
iiI). Cloning a Repo
iv). How to create a Pull Request
2.Also, we can give the links for git installation  
3.We can also add Style Guides for Git Commit Messages
These things will help people new to opensource understand clearly on how to create an issue and how to create a PR.

**Comment by kavania2002** [comment]
Good, I like it. Go on and do please join the discord channel.

**Comment by muthuannamalai12** [comment]
> Good, I like it. Go on and do please join the discord channel.

Sure

**Comment by kavania2002** [comment]
And do write in it that new issues are always welcome.

**Comment by muthuannamalai12** [comment]
> And do write in it that new issues are always welcome.

Ok
