### ISSUE TITLE
no such table: customer_product

### ISSUE THREAD

**Issue by prajaktanandawade** [kavania2002/MobiMart#14]
Request Method: | GET
-- | --
http://localhost:8000/
3.1.6
OperationalError
no such table: customer_product
C:\Users\CHIKU\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\backends\sqlite3\base.py, line 413, in execute
C:\Users\CHIKU\AppData\Local\Programs\Python\Python39\python.exe
3.9.1
['C:\\Users\\CHIKU\\Desktop\\MobiMart\\MobiMart',  'C:\\Users\\CHIKU\\AppData\\Local\\Programs\\Python\\Python39\\python39.zip',  'C:\\Users\\CHIKU\\AppData\\Local\\Programs\\Python\\Python39\\DLLs',  'C:\\Users\\CHIKU\\AppData\\Local\\Programs\\Python\\Python39\\lib',  'C:\\Users\\CHIKU\\AppData\\Local\\Programs\\Python\\Python39',  'C:\\Users\\CHIKU\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages']
Sun, 14 Feb 2021 07:02:11 +0000

Git cloned and run the django server and this error has occured.

**Comment by kavania2002** [comment]
```
python manage.py migrate --run-syncdb
```
Try using this.

**Comment by kavania2002** [comment]
And do join the discord
