### ISSUE TITLE
Improve alignment between phones

### ISSUE THREAD

**Issue by kavania2002** [kavania2002/MobiMart#18]
**Describe the bug**

The space between rows is not enough. Make some changes and align the phones properly. The mobile phone size are too variable. Make sure they are of same size.

**Expected behavior**

The space between phones must be enough. Make sure mobile phones are of same size.

**Screenshots**

![errorAlignment](https://user-images.githubusercontent.com/72624080/107900824-2e5c1280-6f68-11eb-9ff2-8cf1c8b6fbff.PNG)

**Additional context**

New added features are always welcome. Thank you and enjoy coding.

**Comment by arbazalam01** [comment]
Can you assign this to me

**Comment by kavania2002** [comment]
Yes sure. Thanks.
And happy coding.
