### ISSUE TITLE
Find phone which matches with Background

### ISSUE THREAD

**Issue by kavania2002** [kavania2002/MobiMart#19]
**Describe the bug**
The iPhone mobile phones are having white background but the parent background is black, which makes the website odd.

**Expected behavior**
The background must also be black.

**Screenshots**
![errorBG](https://user-images.githubusercontent.com/72624080/107901001-9ca0d500-6f68-11eb-853b-0d794316a1f9.PNG)

**Additional context**
New features are always welcome. Thank you and enjoy coding.

**Comment by swetakb15** [comment]
can I  work on this issue?

**Comment by kavania2002** [comment]
Yeah sure. See to it that now there are many phones of I think 5 6 companies.
Enjoy coding.

**Comment by swetakb15** [comment]
Is there any deadline for it?
