### ISSUE TITLE
Add more mobile phones

### ISSUE THREAD

**Issue by kavania2002** [kavania2002/MobiMart#2]
As a admin you can add more mobile phones

It might be of:
1. Apple
2. Samsung

Spelling of company name must be according to the project, only then it would work. 

###### It must be hd (to look good) and from appropriate site.

**Comment by arbazalam01** [comment]
Can i work on this issue also.

**Comment by kavania2002** [comment]
Yeah sure. But be sure that complete all in minimum amount of time.
And I request you to create pr for each issues. I mean commit changes after one of your pr is merged. It will be helpful for me. Thanks😊

**Comment by arbazalam01** [comment]
Is images are of different size?

**Comment by kavania2002** [comment]
No, size will not matter because I have already set the width and height of the mobile phones. Make sure you select HD images.

**Comment by arbazalam01** [comment]
but in my local machine it shows images of different size.

**Comment by kavania2002** [comment]
Can we have this discussion in discord, because there it would be easier?

**Comment by kavania2002** [comment]
Hey @arbazalam01, I have added the 6 phones. You can add more now.
