### ISSUE TITLE
Add new Smartphones company

### ISSUE THREAD

**Issue by kavania2002** [kavania2002/MobiMart#3]
If you add a new smartphone company then you need to add extra if statement. 

Like if your company name is Samsung then,

```
compName == "Samsung"
```

**Comment by Akash20x** [comment]
Can you please assign me this issue as a part of Cross Woc. I would be very happy to do it

**Comment by kavania2002** [comment]
Can you please provide me the number of days you will take to complete?

**Comment by Akash20x** [comment]
I will do in 2 days.

Hey, I accidentally clicked on unassigned button 
You can please reassign me

**Comment by Akash20x** [comment]
Just an update

I will add 5-6 companies name with each 3 mobile phones with image and price

Sorry for taking too much time as I am busy with other issues.. 

I will do the pull request soon..

**Comment by kavania2002** [comment]
Yeah yeah sure. Don't forget to add sqlite3.db also, because without that mobile phones won't appear.
And you should use common username and passw for admin login. (given in readme).
