### ISSUE TITLE
Icon for showing number of Products in Cart

### ISSUE THREAD

**Issue by kavania2002** [kavania2002/MobiMart#31]
**Is your feature request related to a problem? Please describe.**
When the user adds the mobile to cart, he/she doesn't know how many smartphones has been added.

**Describe the solution you'd like**
You can add number of mobiles added on the cart symbol.

**Additional context**
The icons must be attractive, and should be adjustable with dark/light mode.

**Comment by arbazalam01** [comment]
Can i work on this issue.

**Comment by kavania2002** [comment]
Yeaah @arbazalam01, you can work on this issue first.

**Comment by arbazalam01** [comment]
Please close this issue and also update contributors.md file

**Comment by kavania2002** [comment]
Yes yes sure... thanks for reminding.
