### ISSUE TITLE
Samsung : Add to Cart Btn

### ISSUE THREAD

**Issue by kavania2002** [kavania2002/MobiMart#34]
**Describe the bug**
The button for add to cart in samsung section is odd. It's not the same like others.

**Expected behavior**
It should be made same like others. The background color must be removed.

**Screenshots**

The issue :
![samsungErrorBtn](https://user-images.githubusercontent.com/72624080/108385950-2afbac00-7232-11eb-9ab7-5dbf973988a0.PNG)

The solved :
![solutionBtn](https://user-images.githubusercontent.com/72624080/108386073-4c5c9800-7232-11eb-8949-bc2b8b522bba.PNG)

**Comment by Sloth-Panda** [comment]
@kavania2002  can I work on this issue?

**Comment by swetakb15** [comment]
@kavania2002 Can I work on it?

**Comment by kavania2002** [comment]
Yeah @swetakb15 , you can work on this.

**Comment by kavania2002** [comment]
@swetakb15 start working on this, we will see later that who needs to be assigned the other issue.

**Comment by kavania2002** [comment]
hey @swetakb15, what's the status?

**Comment by swetakb15** [comment]
@kavania2002 done, can you please check it once?
