### ISSUE TITLE
Improve UI/UX for Cart Page

### ISSUE THREAD

**Issue by kavania2002** [kavania2002/MobiMart#35]
It would be good if the Cart Page also looks good, it should match with the homepage and it's colors and all.
Do whatever way you want but it should be awesome.

**Comment by Sloth-Panda** [comment]
@kavania2002 would like to work on this

**Comment by swetakb15** [comment]
@kavania2002 Can I work on this?

**Comment by arbazalam01** [comment]
Can i work on this issue.

**Comment by kavania2002** [comment]
Who would like to work on this?

**Comment by arbazalam01** [comment]
can you assign this to me

**Comment by kavania2002** [comment]
Yeah sure, go on.
Happy Coding.

**Comment by kavania2002** [comment]
Any update on this?

**Comment by arbazalam01** [comment]
Can you please give  me 2 days to complete this.

**Comment by kavania2002** [comment]
Yeah sure.
