### ISSUE TITLE
Improve UI/UX for Shipping/Payment Page

### ISSUE THREAD

**Issue by kavania2002** [kavania2002/MobiMart#39]
It would be good if the Cart Page also looks good, it should match with the homepage and it's colors and all.
Do whatever way you want but it should be awesome.

**Comment by Aayushpatil77** [comment]
Can I work on this issue as a part of CrossWOC ?

**Comment by kavania2002** [comment]
Yeah sure. Go on.
Happy Coding.

**Comment by kavania2002** [comment]
This is issue is open to all.
Anyone?

**Comment by arbazalam01** [comment]
Can you assign this to me

**Comment by kavania2002** [comment]
Ohk go on. Thanks.
