### ISSUE TITLE
Light Theme & Dark Theme

### ISSUE THREAD

**Issue by kavania2002** [kavania2002/MobiMart#4]
Change all the colors according to light theme and dark theme.

Insert a toggle button for respective theme.

If possible, add code to check system theme and set accordingly.

**Comment by arbazalam01** [comment]
Can i work on this issue.

**Comment by kavania2002** [comment]
Hey you are going too fast. Go slow dude. First you work on other issues. There are many things to do in project. Let others also contribute. If no one is ready then at the end you will be assigned.

**Comment by arbazalam01** [comment]
Ok

**Comment by kavania2002** [comment]
Hey do you want to work on this issue? @arbazalam01

**Comment by arbazalam01** [comment]
Yes

**Comment by kavania2002** [comment]
Ohk go on.

**Comment by kavania2002** [comment]
Hey what's the report?

**Comment by arbazalam01** [comment]
I am working on it
