### ISSUE TITLE
A Good Logo

### ISSUE THREAD

**Issue by kavania2002** [kavania2002/MobiMart#40]
Make a good logo, which attracts people.
You can make two logo, one for light and another for dark mode.

**Comment by himanshu007-creator** [comment]
I would like to work on this issue. Please assign me this. I am having exams rn so will be able to do it after 20th march only.
Thanks

**Comment by kavania2002** [comment]
Then I think you should come after 20th March only. 
If someone comes before 20th March, then I will assign him/her.

**Comment by ayushrastogi689** [comment]
I would like to work on this issue please assign it to me.

**Comment by kavania2002** [comment]
Ohk sure. Go on.

**Comment by yashlikescode** [comment]
You need a favicon or logo to be displayed on the website? @kavania2002 
because i would like to design the favicon

**Comment by kavania2002** [comment]
Ohk so @kmryashasvi let @ayushrastogi689 create the logo first, then accordingly @kmryashasvi you can create the favicon, for this create a new issue (only when logo is set)
