### ISSUE TITLE
Add animation to website

### ISSUE THREAD

**Issue by kavania2002** [kavania2002/MobiMart#41]
You can JS to animate the site, like when scrolling the phone appears and many more interesting things.
Make it more dynamic.

**Comment by Akash20x** [comment]
Please assign me this issue as a part of Cross Woc

**Comment by kavania2002** [comment]
Ohk go on.
Happy coding.

**Comment by Akash20x** [comment]
Sorry I withdraw from this issue

As this project does not work properly on my system and migrations didn't work now and I can't change python version and dependencies as it effects other projects..

**Comment by kavania2002** [comment]
Ohkay as you wish, but you can create a virtual environment I guess

**Comment by Akash20x** [comment]
I tried that but it fails and this website is unstructured shown in my system.
You can assign someone else where this website works properly

**Comment by arbazalam01** [comment]
can i work on this issue

**Comment by kavania2002** [comment]
Yes go on
