### ISSUE TITLE
Add MobiMart logo in title bar

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [kavania2002/MobiMart#44]
<img align="center" alt="Coding" width="100%" height="300" src="https://i.postimg.cc/9Fhnssyk/title-icon.png](https://postimg.cc/F1TpLWWb">

**Comment by QAZIMAAZARSHAD** [comment]
Hey @kavania2002,
This is Qazi Maaz Arshad, I am a CrossWoC 2021 participant. Your project is very impressive, I want to add an icon in title bar, please assign me this issue.

**Comment by kavania2002** [comment]
Thanks man and good idea.
You can work on it. Go on.

**Comment by QAZIMAAZARSHAD** [comment]
@kavania2002  I have added MobiMart logo in title bar of all pages and have sent the pull request.
Please review, and this is my first time contributing to open source and creating a pull request please correct me if I had made any mistakes.

**Comment by kavania2002** [comment]
You have create so many pull request. You had to make just one Pull Request. And you have created so many branches too, that's why each branch created new pull request.

**Comment by QAZIMAAZARSHAD** [comment]
Okk, so I have to commit all changes in my main branch and then create a pull request.

**Comment by kavania2002** [comment]
Yes, exactly. You got it right now.

**Comment by QAZIMAAZARSHAD** [comment]
Done, @kavania2002  review last pull request #51 .

**Comment by kavania2002** [comment]
Yeah I will review in a few minutes, could you please close rest of the pull request.
