### ISSUE TITLE
I will add name and photo of maintainer in the end of readme file of your repo

### ISSUE THREAD

**Issue by yashlikescode** [kavania2002/MobiMart#53]
like the one mentioned below 
![image](https://user-images.githubusercontent.com/66861659/110197214-15ac9180-7e70-11eb-97d6-b6028d430dbe.png)

**Comment by kavania2002** [comment]
Yeah sure. Go on.

**Comment by yashlikescode** [comment]
i can also add names of contributors like this,
![image](https://user-images.githubusercontent.com/66861659/110202934-89ab6180-7e91-11eb-9f9d-c352a204aa71.png)
but you have to set difficulty level of this issue for this

**Comment by yashlikescode** [comment]
please tell me what you think

**Comment by kavania2002** [comment]
But you can go on. It will be an easy issue still.

**Comment by yashlikescode** [comment]
Thanks, pr will be requested soon
