### ISSUE TITLE
Add a creative footer in website

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [kavania2002/MobiMart#55]
Footer is missing

**Comment by QAZIMAAZARSHAD** [comment]
I want to add a footer to MobiMart, please assign me this issue.

**Comment by kavania2002** [comment]
Ohk sure go on.
Nice idea.

**Comment by QAZIMAAZARSHAD** [comment]
<img align="center" alt="Coding" width="100%" height="300" src="https://i.postimg.cc/W1dFrMHg/Screenshot-64.png](https://postimg.cc/mPGgWFRg">


Footer Created, you can review @kavania2002

**Comment by QAZIMAAZARSHAD** [comment]
@kavania2002 can you tell me how can I sync my forked repo with your original repo ?

**Comment by kavania2002** [comment]
Can we talk on discord?

**Comment by QAZIMAAZARSHAD** [comment]
sure
