### ISSUE TITLE
Improve UI/UX for the forms

### ISSUE THREAD

**Issue by kavania2002** [kavania2002/MobiMart#6]
Update the login and registration pages.

1. Change the font size, font family
2. Add more bootstrap in it

Do something that makes attractive.

**Comment by Akash20x** [comment]
Can you please assign me this issue as a part of Cross Woc. I would be very happy to do it

**Comment by kavania2002** [comment]
Make it look beautiful @Akash20x

**Comment by Akash20x** [comment]
Sure, I will work for it

**Comment by Hritikkumar** [comment]
Hi Sir, I want to work on this issue. Please assign it to me.

**Comment by kavania2002** [comment]
Sorry @Hritikkumar, it's already been assigned. Can you come up with more ideas and then create an issue for it.

**Comment by kavania2002** [comment]
Hey, @Akash20x what's the report?

**Comment by Akash20x** [comment]
I already worked on it, Need to do some more changes and I will send pull request in today's evening

**Comment by Akash20x** [comment]
I sended the pull request ,please verify it

**Comment by kavania2002** [comment]
Yeah, let me verify it.
