### ISSUE TITLE
Modify navigation bar

### ISSUE THREAD

**Issue by ayushrastogi689** [kavania2002/MobiMart#64]
Currently the website has a big size navigation bar which doesn't seems  good/attractive. 

And we cannot differentiate between the navigation bar and the whole website. Login, Create Account and Light/Dark Mode are not arranged at a decent defined place in nav bar.
 
I am attaching  a sample image of a portfolio just to show how the navigation bar should look.

## Current Navigation Bar

![ss9](https://user-images.githubusercontent.com/66988298/110637686-b0400400-81d3-11eb-8a40-cf7e88e8cc9a.png)

## Screenshot 
![Nav 1](https://user-images.githubusercontent.com/66988298/110637445-69520e80-81d3-11eb-89b7-6d167e913bf0.png)

**Comment by ayushrastogi689** [comment]
I would like to work on this issue please assign me this issue.

**Comment by kavania2002** [comment]
Very nice idea. Go ahead.

**Comment by kavania2002** [comment]
What's the status?

**Comment by ayushrastogi689** [comment]
> What's the status?

I will open a PR today.
