### ISSUE TITLE
Add condition for Creating Password

### ISSUE THREAD

**Issue by kavania2002** [kavania2002/MobiMart#7]
Change the code for Password check:

1. Must be 8 - 20 characters of length
2. Must have atleast one capital letters and lowercase letters and numbers
3. Only accepted @, !, $ (like this type) of characters

**Comment by arbazalam01** [comment]
can you assign this task to me.

**Comment by Akash20x** [comment]
Can you please assign me this issue as a part of Cross Woc. I would be very happy to do it

**Comment by kavania2002** [comment]
@arbazalam01 Can you please give me number of days you will take to complete this?

**Comment by arbazalam01** [comment]
I need 2 days for this task although I will try my best for doing this ASAP.

**Comment by kavania2002** [comment]
Good. And enjoy coding.

**Comment by arbazalam01** [comment]
Thank You for assigning.
